services:
  db:
    ports:
      - '${DB_PORT}:5432'

  adminer:
    image: adminer
    container_name: safevault_adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
    depends_on:
      - db
